version: "3.7"

services:
  nginx:
    depends_on: 
      - wordpress
    build:
      context: ./nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: "nginx"
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
     - wordpress_website:/var/inception_wordpress/wordpress
    restart: always

  wordpress:
    depends_on: 
     - mariadb
    build:
      context: ./wordpress
      args:
        SQL_NAME: ${SQL_NAME}
        SQL_USER: ${SQL_USER}
        SQL_PASS: ${SQL_PASS}
        SQL_HOST: ${SQL_HOST}
    container_name: "wordpress"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMINPASS=${WP_ADMINPASS}
      - WP_ADMINMAIL=${WP_ADMINMAIL}
      - WP_USER=${WP_USER}
      - WP_USERPASS=${WP_USERPASS}
      - WP_USERMAIL=${WP_USERMAIL}
      - WP_TITLE=${WP_TITLE}
    networks:
     - inception_network
    volumes:
     - wordpress_website:/var/inception_wordpress/wordpress
    restart: always

  mariadb:
    build: 
      context: ./mariadb
      args:
        SQL_NAME: ${SQL_NAME}
        SQL_USER: ${SQL_USER}
        SQL_PASS: ${SQL_PASS}
        SQL_HOST: ${SQL_HOST}
        SQL_ROOTPASS: ${SQL_ROOTPASS}
    container_name: "mariadb"
    networks:
      - inception_network
    volumes:
    - wordpress_database:/var/lib/mysql
    restart: always



networks:
  inception_network:
      name: inception_network


volumes:
  wordpress_website:
    name: wordpress_website
    driver: local
    driver_opts:
      device: /home/kzennoun/data/inception_volumes/wordpress_website
      o: bind
      type: none

  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
      device: /home/kzennoun/data/inception_volumes/wordpress_database
      o: bind
      type: none
